spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/preproject222
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

maxValue: 3
server:
  error:
    include-message: always

sort:
  enabled:
    - id
    - manufacturer
    - model
    - year